version: "3.8"

services:
  python3:
    container_name: hram_bot
    restart: always
    env_file:
      - /home/orlow/hram/.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/orlow/hram:/app/hdd
    networks:
      - my_network

  database:
    container_name: postgres
    image: postgres:14.5-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres/data
    env_file:
      - /home/orlow/postgres/.env
    networks:
      - my_network  

volumes:
  postgres:
networks:
  my_network:  
