version: "3.8"

services:
  python3:
    container_name: hramiosif_bot
    restart: always
    env_file:
      - /home/orlow/hram/.env
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - /home/orlow/hram:/app/hdd
