name: Deploy iosif bot

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          clean: 'false'

      - name: docker compose
        run: docker compose -f docker-compose.yml up --build --force-recreate -d
