name: Deploy iosif bot
env:
  BOT_TOKEN: ${{ env.BOT_TOKEN }}
  ADMINISTRATOR_NIKITA_1: ${{ env.ADMINISTRATOR_NIKITA_1 }}
  ADMINISTRATOR_NIKITA_2: ${{ env.ADMINISTRATOR_NIKITA_2 }}
  ADMINISTRATOR_SASHA: ${{ env.ADMINISTRATOR_SASHA }}
  ADMINISTRATOR_PASHA: ${{ env.ADMINISTRATOR_PASHA }}
  PG_NAME: ${{ env.PG_NAME }}
  PG_USER: ${{ env.PG_USER }}
  PG_PASS: ${{ env.PG_PASS }}
  PG_HOST: ${{ env.PG_HOST }}
  PG_PORT: ${{ env.PG_PORT }}

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose
        run: docker compose -f docker-compose.yml -p mamod_web up --build --force-recreate -d
      - name: asd
        run: echo ${{vars}} ${{secrets}}
