name: Deploy iosif bot

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    env:
      BOT_TOKEN: ${{ vars.BOT_TOKEN }}
      ADMINISTRATOR_NIKITA_1: ${{ vars.ADMINISTRATOR_NIKITA_1 }}
      ADMINISTRATOR_NIKITA_2: ${{ vars.ADMINISTRATOR_NIKITA_2 }}
      ADMINISTRATOR_SASHA: ${{ vars.ADMINISTRATOR_SASHA }}
      ADMINISTRATOR_PASHA: ${{ vars.ADMINISTRATOR_PASHA }}
      PG_NAME: ${{ vars.PG_NAME }}
      PG_USER: ${{ vars.PG_USER }}
      PG_PASS: ${{ vars.PG_PASS }}
      PG_HOST: ${{ vars.PG_HOST }}
      PG_PORT: ${{ vars.PG_PORT }}
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose
        run: docker compose -f docker-compose.yml -p mamod_web up --build --force-recreate -d
      - name: aqqwe
        run: echo $GITHUB_ENV

