name: Deploy iosif bot

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
#      - name: checkout repo
#        uses: actions/checkout@v3
      - name: docker compose
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMINISTRATOR_NIKITA_1: ${{ secrets.ADMINISTRATOR_NIKITA_1 }}
          ADMINISTRATOR_NIKITA_2: ${{ secrets.ADMINISTRATOR_NIKITA_2 }}
          ADMINISTRATOR_SASHA: ${{ secrets.ADMINISTRATOR_SASHA }}
          ADMINISTRATOR_PASHA: ${{ secrets.ADMINISTRATOR_PASHA }}
          PG_NAME: ${{ secrets.PG_NAME }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
        run: docker compose -f docker-compose.yml -p mamod_web up --build --force-recreate -d
      - name: asd
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMINISTRATOR_NIKITA_1: ${{ secrets.ADMINISTRATOR_NIKITA_1 }}
          ADMINISTRATOR_NIKITA_2: ${{ secrets.ADMINISTRATOR_NIKITA_2 }}
          ADMINISTRATOR_SASHA: ${{ secrets.ADMINISTRATOR_SASHA }}
          ADMINISTRATOR_PASHA: ${{ secrets.ADMINISTRATOR_PASHA }}
          PG_NAME: ${{ secrets.PG_NAME }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
        run: echo ${{ secrets.BOT_TOKEN }}
      - name: Get secret from base64
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMINISTRATOR_NIKITA_1: ${{ secrets.ADMINISTRATOR_NIKITA_1 }}
          ADMINISTRATOR_NIKITA_2: ${{ secrets.ADMINISTRATOR_NIKITA_2 }}
          ADMINISTRATOR_SASHA: ${{ secrets.ADMINISTRATOR_SASHA }}
          ADMINISTRATOR_PASHA: ${{ secrets.ADMINISTRATOR_PASHA }}
          PG_NAME: ${{ secrets.PG_NAME }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
        run: |
          echo import certificate from secrets and regenerate the file
          echo $BOT_TOKEN > $RUNNER_TEMP/.env
          echo $ADMINISTRATOR_NIKITA_1 > $RUNNER_TEMP/.env
          echo $ADMINISTRATOR_NIKITA_2 > $RUNNER_TEMP/.env
          echo $ADMINISTRATOR_SASHA > $RUNNER_TEMP/.env
          echo $ADMINISTRATOR_PASHA > $RUNNER_TEMP/.env
          echo $PG_NAME > $RUNNER_TEMP/.env
          echo $PG_USER > $RUNNER_TEMP/.env
          echo $PG_PASS > $RUNNER_TEMP/.env
          echo $PG_HOST > $RUNNER_TEMP/.env
          echo $PG_PORT > $RUNNER_TEMP/.env
